# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20161105_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='createtime',
        ),
    ]
